# Generated by Django 4.1 on 2023-09-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectRecognition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('result_type', models.IntegerField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'object_recognition',
                'managed': False,
            },
        ),
    ]
